server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CATALOG-SERVICE
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog/category/**,/catalog/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: CATALOG-SERVICE
                fallbackUri: forward:/catalogServiceFallback
        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/**
          filters:
            - name: CircuitBreaker
              args:
                name: IDENTITY-SERVICE
                fallbackUri: forward:/catalogServiceFallback        

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost